#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/resource-request.XXXXXX)
cat > $payload <&0

concourse_url=$(jq -r '.source.concourse_url // ""' < $payload)
username=$(jq -r '.source.username // ""' < $payload)
password=$(jq -r '.source.password // ""' < $payload)
pipeline=$(jq -r '.source.pipeline // ""' < $payload)
job=$(jq -r '.source.job // ""' < $payload)

echo -e "$username\n$password\n" | fly -t savannah login --concourse-url $concourse_url
fly -t savannah builds -j $pipeline/$job > $pipeline.$job.txt

line=$(head -n 1 $pipeline.$job.txt)
ref=$(echo $line | cut -d " " -f 3)
status=$(echo $line | cut -d " " -f 4)

if [[ $status = "started" ]]
then
    echo '[{ "ref": "'$curr_ref'" }]' >&3
else
    if [ "${curr_ref}" = "${ref}" ]; then
        echo '[{ "ref": "'$curr_ref'" }]' >&3
    else
        echo '[{ "ref": "'$curr_ref'" }, { "ref": "'$ref'" }]' >&3
    fi
fi
