#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

#REF="cba8422359aa242694978f581cf3f0c754ec5542"
#jq -n "{version: {ref: $REF},metadata: {}}" >&3

git clone --branch ci-test ssh://git@stash.zipcar.com:7999/cheet/pipeline-test-app.git $1
cd $1
git checkout cba8422359aa242694978f581cf3f0c754ec5542

jq -n '{
  "version": { "ref": "cba8422359aa242694978f581cf3f0c754ec5542" },
  "metadata": [
    { "name": "commit", "value": "cba8422359aa242694978f581cf3f0c754ec5542" },
    { "name": "author", "value": "Ivan Vojinovic" }
  ]
}'